FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  git curl procps \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@latest

RUN mkdir -p /app/anis-shared /app/anis-backend

WORKDIR /app/anis-backend

EXPOSE 5000

CMD ["pnpm", "dev"]
