FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  git curl procps \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@latest

WORKDIR /app/anis-backend

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

EXPOSE 5000

CMD ["pnpm", "dev"]

